/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type CreditDetails200Person = {
  adult?: boolean;
  id?: number;
  name?: string;
  original_name?: string;
  media_type?: string;
  popularity?: number;
  gender?: number;
  known_for_department?: string;
  profile_path?: string;
};
