/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type SearchPersonParams = {
query: string;
include_adult?: boolean;
language?: string;
page?: number;
};
