/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type TvSeriesAggregateCredits200CastItemRolesItem = {
  credit_id?: string;
  character?: string;
  episode_count?: number;
};
