/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type TvSeriesDetails200ProductionCountriesItem = {
  iso_3166_1?: string;
  name?: string;
};
