/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type TvSeriesDetails200SpokenLanguagesItem = {
  english_name?: string;
  iso_639_1?: string;
  name?: string;
};
